name: Build ARM64 Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build ARM64 Image and Load It
      run: docker buildx build --platform linux/arm64 --load -t vpn-builder .

    - name: Create Container from Image
      run: docker create --name extract vpn-builder

    - name: Extract ARM64 Executable
      run: docker cp extract:/app/vpn_executable vpn_executable

    - name: Remove Temporary Container
      run: docker rm extract

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: vpn_executable
        path: vpn_executable
