name: Build and Upload Artifact
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build project
        run: |
          # (Build steps would go here)
          mkdir -p build/output
          echo "Hello world!" > build/output/hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact            # Name of the artifact
          path: build/output           # Path to file or directory to upload
          retention-days: 7            # (Optional) Retain artifact for 7 days
          if-no-files-found: error     # (Optional) Fail if no files found at path
